# Generated by Django 4.0.5 on 2022-06-20 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('zipCode', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=40)),
                ('displayName', models.CharField(max_length=40)),
                ('tagline', models.CharField(max_length=30)),
                ('contactNumber', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verificaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.CharField(max_length=30)),
                ('contactNumber', models.IntegerField()),
                ('passport', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='verification/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancing.address')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Freelancing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedlin', models.URLField()),
                ('behance', models.URLField()),
                ('dribble', models.URLField()),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Freelancing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Freelancing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('priceType', models.CharField(choices=[('HOURLY RATE', 'HOURLY RATE'), ('HALF DAY RATE', 'HALF DAY RATE'), ('FULL DAY RATE', 'FULL DAY RATE')], default='HOURLY RATE', max_length=40)),
                ('location', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('projectPeriod', models.CharField(blank=True, choices=[('START_IMMEDIATE', 'SI'), ('JOB_DATE', 'JD')], max_length=250)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='verification/')),
                ('links', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('expertise', models.ManyToManyField(blank=True, to='Freelancing.skill')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Freelancing.project')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('link', models.URLField()),
                ('files', models.FileField(upload_to='Files/')),
                ('description', models.TextField()),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Freelancing.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='skills',
            field=models.ManyToManyField(to='Freelancing.skill'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freelancing.customer')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='customerAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Freelancing.customer'),
        ),
    ]
