# Generated by Django 4.0.5 on 2022-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
