# Generated by Django 4.0.5 on 2022-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancing', '0002_alter_projectdetail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='is_start_immediately',
            field=models.BooleanField(default=False),
        ),
    ]
