# Generated by Django 4.0.5 on 2022-06-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancing', '0003_projectdetail_is_start_immediately'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='project_status',
            field=models.BooleanField(default=True),
        ),
    ]
