# Generated by Django 4.0.5 on 2022-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancing', '0004_projectdetail_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='technology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
