# Generated by Django 4.0.5 on 2022-06-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancing', '0005_projectdetail_company_projectdetail_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='project_status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive'), ('Trash', 'trash')], default='Active', max_length=40),
        ),
    ]
