# Generated by Django 4.0.5 on 2022-06-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancing', '0006_alter_projectdetail_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customerAddress',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contactNumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='priceType',
            new_name='price_type',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='projectPeriod',
            new_name='project_period',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='verificaion',
            old_name='contactNumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='verificaion',
            old_name='yourName',
            new_name='your_name',
        ),
    ]
