# Generated by Django 4.0.5 on 2022-06-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancing', '0007_rename_customeraddress_address_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificaion',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
