# Generated by Django 4.0.5 on 2022-06-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0004_alter_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=100)),
                ('date_format', models.CharField(max_length=100)),
                ('time_format', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
