# Generated by Django 4.0.5 on 2022-06-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0005_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='currency_symbol',
            field=models.CharField(choices=[('$', '$'), ('£', '£'), ('₹', '₹')], default='$', max_length=10),
        ),
        migrations.AlterField(
            model_name='localization',
            name='date_format',
            field=models.CharField(choices=[('15 May 2016', 'DMY'), ('15/05/2016', 'DMYA'), ('15.05.2016', 'DMYB'), ('15-05-2016', 'DMYC')], default='15 May 2016', max_length=100),
        ),
        migrations.AlterField(
            model_name='localization',
            name='time_format',
            field=models.CharField(choices=[('12 Hours', '12 Hours'), ('24 Hours', '24 Hours')], default='12 Hours', max_length=100),
        ),
        migrations.AlterField(
            model_name='localization',
            name='timezone',
            field=models.CharField(choices=[('(UTC +5:45)Asia/Katmandu', 'Katmandu'), ('(UTC +5:30)India', 'India')], default='(UTC +5:45)Asia/Katmandu', max_length=100),
        ),
    ]
