# Generated by Django 4.0.5 on 2022-06-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0006_alter_localization_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='date_format',
            field=models.CharField(choices=[('15 May 2016', '15 May 2016'), ('15/05/2016', '15/05/2016'), ('15.05.2016', '15.05.2016'), ('15-05-2016', '15-05-2016')], default='15 May 2016', max_length=100),
        ),
        migrations.AlterField(
            model_name='localization',
            name='timezone',
            field=models.CharField(choices=[('(UTC +5:45)Asia/Katmandu', '(UTC +5:45)Asia/Katmandu'), ('(UTC +5:30)India', '(UTC +5:30)India')], default='(UTC +5:45)Asia/Katmandu', max_length=100),
        ),
    ]
