# Generated by Django 4.0.5 on 2022-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0007_alter_localization_date_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=10)),
                ('braintree_token_key', models.CharField(max_length=100)),
                ('braintree_merchant_id', models.CharField(max_length=100)),
                ('braintree_public_key', models.CharField(max_length=100)),
                ('braintree_private_key', models.CharField(max_length=100)),
                ('paypal_app_id', models.CharField(max_length=100)),
                ('paypal_secret_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=10)),
                ('gateway_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('rest_key', models.CharField(max_length=100)),
            ],
        ),
    ]
